### ISSUE TITLE
How to calculate BLUE and ROUGE metrics?

### ISSUE THREAD

**Issue by ithieund** [shengqiangzhang/transformer-pointer-generator-for-english-dataset#1]
Hello @shengqiangzhang , can you give me some instruction to calculate the BLUE and ROUGE metrics after having the decoding result when running command python pred.py --ckpt log/conala/trans_pointerE75L1.82-75 --test dataset/conala/test.csv --vocab dataset/conala/vocab --vocab_size 4137 --maxlen1 200 --maxlen2 50

<img width="655" alt="image" src="https://user-images.githubusercontent.com/4217195/155868415-fae6301b-23aa-4a26-a19d-e3c4b78709d6.png">

Thank you.

**Comment by shengqiangzhang** [comment]
Hi @ithieund , Our code is modified based on [transformer-pointer-generator](https://github.com/xiongma/transformer-pointer-generator). You may need to contact the author of the original repo for help.
